name: oltp_warehouse
version: "1.0.0"
config-version: 2

profile: oltp_warehouse

model-paths: ["dbt/models"]
macro-paths: ["dbt/macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  oltp_warehouse:
    silver:
      +materialized: external
      +format: parquet
